on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+*"

env:
  TAG_VERSION: ${{ github.ref_name }}
  GO_VERSION: "1.19.3"

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
            ./vendor
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-
      - uses: actions/setup-go@v3
        with:
          go-version: ${{ env.GO_VERSION }}

      - name: Go mod vendor
        run: go mod vendor

      - name: Build
        run: |
          go build -o out/hue-hook-amd64 ./...
          GOARCH=arm GOARM=7 go build -o out/hue-hook-armv7 ./...

      - name: Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "out/*"
          body: "${{ env.TAG_VERSION }}+${{ env.VERSION_CODE }}"
          token: ${{ secrets.GITHUB_TOKEN }}
          generateReleaseNotes: true